jdbc.url=jdbc:postgresql://localhost:5432/trainee_01_answers
jdbc.driver=org.postgresql.Driver
jdbc.user=trainee_01
jdbc.password=01

ontop.mapping.file=OMOP-postgresql.obda
ontop.owl.file=../ontology/OMOP.ttl
